### ISSUE TITLE
Suggestions for improvement of the template

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron_module_template#3]
**Summary**

Some suggestions for improving this template  based on my experience using this template to create [pyiron_electrochemistry](https://github.com/pyiron/pyiron_electrochemistry).

**Detailed Description**

First of all, thank you @jan-janssen and @niklassiemer for developing this. I was able to create a new pyiron module and setup the CI environment seamlessly. Just a couple of minor suggestions for improvements:

1. The bash scripts to be run during the CI workflows need appropriate permissions (see my adaptation [here](https://github.com/pyiron/pyiron_electrochemistry/blob/master/.github/workflows/notebooks.yml#L37))
2. Is there a way to change string `pyiron_module` to the actual module name using some sort of environment variable? This is not that crucial but I think it would make things much easier since this needs to be changed at quite a few places.
3. The workflows for unittests and code coverage is not included currently. It'll be great if we add this as well.

**Comment by jan-janssen** [comment]
You should have access now.

**Comment by sudarsan-surendralal** [comment]
Additional ToDo:

- Environment variable with module name
- Change module name in the _version.py file & the setup.cfg file
- Load repo name from environment
- For pip, codacy, dependabot we need a token (from someone with pyiron runner rights)
- Need to setup conda by yourself

**Comment by niklassiemer** [comment]
Thanks for this issue! In addition to unittest, benchmark tests are also missing.
